spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: honor.preservation@gmail.com
    password: h0n0rpr3s3rv4t10n
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false